### ISSUE TITLE
Exemple of Hidden generation seems to be wrong

### ISSUE THREAD

**Issue by brunodoamaral** [microsoft/guidance#12]
I think that the output for hidden generation on README.me is wrong. Can someone double check it?

https://github.com/microsoft/guidance#hidden-generation

**Comment by slundberg** [comment]
Thanks for the head up! Which one? This is what I see (which seems fine): 
<img width="794" alt="image" src="https://github.com/microsoft/guidance/assets/3740613/4c6f70d0-4bb2-4352-9072-3c10059ab403">

**Comment by brunodoamaral** [comment]
I see a different version. It shows a different image and does not include setting the llm:

https://github.com/microsoft/guidance/blob/b1e656f87abc543c68f3d07057a23f2f5922a878/README.md?plain=1#L554-L568

**Comment by j4acks0n** [comment]
> I see a different version. It shows a different image and does not include setting the llm:
> 
> https://github.com/microsoft/guidance/blob/b1e656f87abc543c68f3d07057a23f2f5922a878/README.md?plain=1#L554-L568

Maybe It's Different Method 
But Yeah You Must Begin From Scratch

**Comment by marcotcr** [comment]
All of the examples in that section of the readme assume you've set a default llm, which we do in [the first example](https://github.com/microsoft/guidance#basic-generation).

Other than that, the code you posted is the same what's above. Of course, the generation will change depending on what LLM you have, so getting that exact output is not important :)

(Please reopen if I'm missing something)

**Comment by DmitriyLeybel** [comment]
![image](https://github.com/microsoft/guidance/assets/6779278/5ff744d9-fda3-43ed-b942-e7974813f4ad)

The hidden block is still showing in the documentation.

Whereas `I will show you an email and a response, and you will tell me if it's offensive.` is being hidden instead within that example.
