### ISSUE TITLE
#select not working with OpenAI LLM

### ISSUE THREAD

**Issue by jprafael** [microsoft/guidance#122]
# The bug

Any prompt with a `#sellect` block fails when using OpenAI llm (specifically `gpt-3.5-turbo` maybe others).

```
Traceback (most recent call last):
  File "redacted/guidance/_program_executor.py", line 94, in run
    await self.visit(self.parse_tree)
  File "redacted/guidance/_program_executor.py", line 429, in visit
    visited_children.append(await self.visit(child, inner_next_node, inner_next_next_node, inner_prev_node, node, parent_node))
  File "redacted/guidance/_program_executor.py", line 429, in visit
    visited_children.append(await self.visit(child, inner_next_node, inner_next_next_node, inner_prev_node, node, parent_node))
  File "redacted/guidance/_program_executor.py", line 396, in visit
    command_output = await command_function(*positional_args, **named_args)
  File "redacted/guidance/library/_assistant.py", line 13, in assistant
    return await role(name="assistant", hidden=hidden, _parser_context=_parser_context)
  File "redacted/guidance/library/_role.py", line 14, in role
    out = await parser.visit(
  File "redacted/guidance/_program_executor.py", line 429, in visit
    visited_children.append(await self.visit(child, inner_next_node, inner_next_next_node, inner_prev_node, node, parent_node))
  File "redacted/guidance/_program_executor.py", line 429, in visit
    visited_children.append(await self.visit(child, inner_next_node, inner_next_next_node, inner_prev_node, node, parent_node))
  File "redacted/guidance/_program_executor.py", line 396, in visit
    command_output = await command_function(*positional_args, **named_args)
  File "redacted/guidance/library/_select.py", line 138, in select
    option_logprobs = await recursive_select([])
  File "redacted/guidance/library/_select.py", line 109, in recursive_select
    logprobs_result = gen_obj["choices"][0]["logprobs"]
KeyError: 'logprobs'
```

# To Reproduce

```python
llm = guidance.llms.OpenAI("gpt-3.5-turbo", token=OPENAPI_KEY)

program = guidance(
"""
{{#user~}}
Take the red or blue pill?
{{~/user}}

{{#assistant~}}
{{#select 'pill'}}Red{{or}}Blue{{/select}}
{{~/assistant}}
""")

result = program(llm=llm)
```

# System info
 - OS: Ubuntu
 - Guidance Version: 0.0.55
 - Python: 3.9.9

**Comment by slundberg** [comment]
Thanks, we should add a better error message. The problem is that OpenAI does not yet support `logprobs` in Chat mode (or partial completions for that matter either), both of which are needed by `select`.

https://github.com/openai/openai-python/issues/248

The best that can be done right now is to use `gen`. Perhaps it would be worth adding some custom workaround, but I think the best we can do right now is just bias to logits.

**Comment by lichtungnitro** [comment]
Chat mode design is so cooool, it is worth adding some support to make this work for non-chat models. The `selec` and other syntax are truly promising, hope it will work with the roles. That truly saves time. For now, I need add extra instruction in prompt to force a chat model to generate JSON or other formatted content, and validate the output again.

**Comment by slundberg** [comment]
Good news. I looked into this more and was able to make it work even when logprobs is not returned. We still can't do partial completions with the OpenAI API (yet), but the select example above now works in 0.0.57.
