### ISSUE TITLE
Allow dynamic removal of history elements to manage token limit

### ISSUE THREAD

**Issue by jakearlen879** [microsoft/guidance#131]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when using this library and encountering the issue of reaching the maximum token limit with gpt-3.5-turbo. The limitation on token count often restricts the amount of historical context I can include, hindering the effectiveness of the generated responses.

**Describe the solution you'd like**
I want to be able to remove certain elements of the history dynamically, allowing me to control the token count and prevent reaching the maximum limit.

**Describe alternatives you've considered**
An alternative I've considered is switching to gpt-4 instead of gpt-3.5-turbo. GPT-4 offers a higher maximum token limit, which would alleviate the issue of reaching the token constraint more frequently. However, GPT-4 comes with a higher cost than GPT-3.5-turbo, which may only be feasible for some users and projects.

**Additional context**
GPT-3.5-turbo has a maximum token limit of 4096 tokens ($0.002 / 1K tokens). Upgrading to gpt-4 offers a higher token limit (8000 tokens) but comes at a higher cost of approximately $0.03 / 1K tokens for prompts and $0.06 / 1K tokens for completions.

**Comment by chrisfentiman** [comment]
Hey @jakearlen879, I just wanted to share a thought with you. Guidance provides us with the tools we need, but ultimately, it's up to us to figure out the best strategy for managing token usage in our model, application, and context. So, it might not be fair to expect Guidance to handle everything for us.

There are many ways to manage token limits with OpenAI, and what works for one model might not be effective for another. It's worth taking a moment to reassess your application architecture and consider why you need to include all that context in memory. Your system might already have a solution in place (e.g., dynamically create the history on new input).

No worries, we're all learning together. Just offering some insight! 😊

**Comment by justinbowes** [comment]
I implemented this in an experiment. As a sketch, it was:

1. Store two copies of history. `summarization_history` is _eligible_ for summarization. `complete_history` is for other purposes (i.e. knowledge extraction). 
2. Initially both copies store all history entries in a list along with the token length of each entry.
3. At each interaction, use the `summarization_history` to populate the prompt's `history`.
4. After each interaction, find whether there is an index `n` in history where the token length sum exceeds summarization threshold.
5. If so, run another program to summarize the first n entries, and replace those entries in `summarization_history` with the summary. (On subsequent runs, the summarization will be `history[0] # existing summary` + `history[1:n] # entries to add to summary`).

Where Guidance helps with this is that you can set roles and stopping conditions such that you can be extremely confident that the summarization is good quality, even with open source LLMs. This was a problem for me even using the built-in summarization features in other frameworks in the past.

**Comment by marcotcr** [comment]
Yep, as @justinbowes mentioned, I doubt we'd be able to come up with some dynamic removal scheme that is generalizable.

But here is a snippet that might be helpful for you, where we define a custom function that counts how many tokens were generated up to a certain point and return a list of variable length based on that (of course it's a toy example, but you should be able to modify it for your own use case). It uses `prefix`, which is a special variable that has all that was generated up to that point.

```python
import tiktoken
import guidance
guidance.llm = guidance.llms.OpenAI("gpt-3.5-turbo")
enc = tiktoken.encoding_for_model("gpt-3.5-turbo")
def rate_limited_content(prefix):
    # Takes a prefix, tokenizes it, and returns one or more questions to ask the user depending on how many tokens we've generated so far
    new_questions = ['Please explain why you think this is a good answer.', 'Please explain why you think this is a bad answer.']
    tokens_used = len(enc.encode(prefix))
    if tokens_used > 100:
        return new_questions[:1]
    return new_questions
    
prompt = guidance(
'''{{#system~}}
You are a helpful assistant.
{{~/system}}

{{#user~}}
{{conversation_question}}
{{~/user}}

{{#assistant~}}
{{gen "answer"}}
{{~/assistant}}

{{#user~}}
{{#each (rate_limited_content prefix)~}}
{{this}}
{{/each}}
{{~/user}}

{{#assistant~}}
{{gen "answer2"}}
{{~/assistant}}
''')
```

Now, here is an example run where the first question is long, and thus we will only add a single question as a followup:
```python
prompt(conversation_question='Whats is the meaning of life??', rate_limited_content=rate_limited_content)
``` 
![image](https://github.com/microsoft/guidance/assets/698010/49d9d6f5-94a2-44eb-8969-6f146b9af8c4)

Here is an example where it is short, and thus both questions get added:
```python
prompt(conversation_question='What is 1+1?', rate_limited_content=rate_limited_content)
```
![image](https://github.com/microsoft/guidance/assets/698010/8c333373-4658-4885-be39-f0f03421f725)

Of course, you could also set a variable with how many tokens you have left and use it to set `max_tokens` when generating. You'd do something like `set 'tokens_left' (budget prefix)`, where budget is a python function that counts how many tokens you have left

**Comment by slundberg** [comment]
Just a heads up, the new `prefix` variable will likely end up being named `@prefix` before we push a release to maintain better alignment with Handlebars special variable names.
