### ISSUE TITLE
OpenAI API key requested when using transformers models

### ISSUE THREAD

**Issue by Ryul0rd** [microsoft/guidance#14]
I'm trying to use a transformers model like so
`model = guidance.llms.Transformers('stabilityai/stablelm-base-alpha-3b', device=0)`
but getting the following error when I try to call the guidance program:
`AssertionError: You must provide an OpenAI API key to use the OpenAI LLM. Either pass it in the constructor, set the OPENAI_API_KEY environment variable, or create the file ~/.openai_api_key with your key in it.`

**Comment by marcotcr** [comment]
I can't replicate, can you please provide the full code snippet?
I run the following with no problems even when I delete my OpenAI api key:
```python
import guidance
model = guidance.llms.Transformers('stabilityai/stablelm-base-alpha-3b', device=0)
p = guidance('''Hello {{gen 'ae'}}''', llm=model)
p()
```

**Comment by marcotcr** [comment]
Ah, as of yesterday we had OpenAI as the default LLM (we don't anymore), I'm guessing you probably didn't set `model` as the LLM for the call (like I did above) or as the default guidance LLM, like this:
```python
guidance.llm = model
```
I'm going to assume that's what it is and close this, but please reopen if this is not it.
