### ISSUE TITLE
The Run Time of Summarization Task by Guidance is much longer than <Map-Reduce Chains> in Langchain and why?

### ISSUE THREAD

**Issue by Tom-0727** [microsoft/guidance#140]
**Is your feature request related to a problem? Please describe.**
The Run Time of Summarization Task by Guidance is much longer than <Map-Reduce Chains> in Langchain and why?
I want to use Guidance to achieve acceleration in Summarization Task, the method using is Map-Reduce
- I try to use two methods: (using text-davinci-003 with {{#each}} command)
````
summary_list = []
def add_below(text):
    summary_list.append(text)

summarization_template = """
Write a concise summary on the content. 
You must include the source of text in the end of the summary, 
for example, [from url1] or [from url2]

{{~#each text_list}}
{{#block hidden=True}}
<Content: {{this}}>
Summary: {{add_below (gen 'summary' temperature=0)}}
{{/block}}
{{/each}}
"""
````
Use 1min 30s

- And use gpt-3.5-turbo with {{#geneach}} command
````
summary_list = []
def add_below(text):
    summary_list.append(text)

summarization_template = """
{{#system~}}
Write a concise summary on the following text. You must include the source of text in the end of the summary, for example, [from url1] or [from url2]
{{~/system}}

{{~#geneach 'summaries' stop=False}}
{{#user~}}
{{set 'this.usr_text' (await 'usr_text')}}
{{~/user}}

{{#assistant~}}
{{add_below (gen 'this.summary' temperature=0)}}
{{~/assistant}}
{{~/geneach}}
"""
for text in texts:
    summary_program(usr_text = text, add_below = add_below)
````
takes 1min 15s

But with Langchain, it takes 40s.  Almost the same generated length.

**Describe the solution you'd like**
- I hope to know why would it be and do we have a better solution for acceleration?

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by slundberg** [comment]
Thanks for sharing! One thing that sticks out to me is that the `geneach` loop does not have `hidden=True` this means each summary becomes part of the prompt for later summaries, when using the OpenAI API this can slow things down.

That said, I think doing some benchmarking here to make sure we don't slow anything down would be great. Do you mind sharing a notebook or file that we can run to test these results directly?

**Comment by Tom-0727** [comment]
> 

Thanks for your kind reply! I have make a pull request for the test notebook. You can check on it. The detail:

# Test between the Summarization Task by Langchain & Guidance
- Detail:
    - Objects: test the performance of summarization between Langchain & Guidance
    - BenchMark: Runtime
    - LLM: OpenAI API - "text-davinci-003"
    - Method: Map-Reduce
        1. Split text into chunks
        2. Do summarization on each chunks and get summaries
        3. Do final summarization on the summaries

- Langchain:
    - using map_reduce_chain - 43.535649061203s

- Guidance:
    - using {{#each}} - 97.12837052345276s
    - using {{#geneach}} - 79.16032338142395s

**Comment by slundberg** [comment]
This was because loops were not parallelized in Guidance. That is now fixed for `each` loops where `hidden=True` is set, and Guidance runs faster there now.
