### ISSUE TITLE
Any More tutorial details about how to use and develop?

### ISSUE THREAD

**Issue by oneTaken** [microsoft/guidance#156]
It seems that this repo is focusing on some limited scope, while many more situation is not supported yet, such as lora/peft/ui/deploy.   
I do not search some useful details to develop more features.

**Comment by marcotcr** [comment]
Correct, we're not touching finetuning at all. If you have specific recommendations for tutorials we are currently missing, please let us know :)

**Comment by XianglongTan** [comment]
> Correct, we're not touching finetuning at all. If you have specific recommendations for tutorials we are currently missing, please let us know :)

Is there any plan of supporting finetuning?
