### ISSUE TITLE
Dynamic max_tokens via external function call

### ISSUE THREAD

**Issue by Arttii** [microsoft/guidance#161]
**Is your feature request related to a problem? Please describe.**
Sometimes I would want to dynamically constrain the `max_tokens` parameter by how much the actually input prompt is already using.

**Describe the solution you'd like**
 Being able to use variables or external functional call in the parameters of `gen` and other?

Maybe this is already possible, but I did not seem to understand how. Thanks for the great library!

**Comment by chrisfentiman** [comment]
@Arttii - you can do this on program startup using tiktoken and making your prompt a `Template` string. 

```python

prompt_str = Template("{{#assistant}}{{gen 'some_gen' max_tokens=$max_tokens}}{{/assistant}}")

token_count = # run num_tokens [example](https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken.ipynb)

prompt_str.substitute(max_tokens=your_max-token_count)

# run the program now with the dynamic token count.
```

[tiktoken example](https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken.ipynb)

This has limitations, like when running in a geneach, but overall - it should work for most usecases.

**Comment by Arttii** [comment]
Thanks for the tip @chrisfentiman !

**Comment by mjedmonds** [comment]
How does this handle the guidance-specific string structure? It seems like this will not given an accurate token count - but is likely close. 

Is there a way to get the the compiled test actually sent to the LLM? It looks like it's stored in `@raw_prefix` during execution. I don't see any obvious exposure of this text without actually executing the guidance program. @slundberg Any ideas?

Thanks in advance!
