### ISSUE TITLE
Custom cache dir

### ISSUE THREAD

**Issue by jprafael** [microsoft/guidance#162]
## Is your feature request related to a problem? Please describe.

Trying to use guidance in the context of an AWS Lambda function.
AWS Lambda file system is read-only except for the `/tmp/` directory.
Using guidance with default parameters fails because of

```
Cache directory "/home/sbx_user1051/.cache/guidance/_openai.diskcache" does not exist and could not be created
```

## Describe the solution you'd like

I'd love if we can customize the cache dir instead of relying only on `platformdirs`.

Currently `cache` objects are static, and some LLMs actually create more than one (e.g. `AzureOpenAI` uses `azure_openai.diskcache` and `_azure_openai.token`, but because it is a child of `OpenAI` it also creates `_openai.diskcache`).

The easy way out would be to check for an env variable (`GUIDANCE_CACHE_DIR`) and use it instead of platformdirs if it is set. Default behaviour would be untouched.

Another alternative, would be to change `cache` objects from static to regular class members, and pass a `cache_dir` option along with the current `caching` flag. This would allow customization without relying on global state. `diskcache` internally is thread/process safe so if the user ends up creating multiple LLMs it would still work as intended.

## Additional context
Happy to submit a PR with the changes once we settle on a design.
What would be your preference?

**Comment by bkamapantula** [comment]
+1 to this feature. I've the same use-case.

**Comment by markmacau** [comment]
In my experience, setting /tmp as the XDG_CACHE_HOME in the AWS Lambda environment variables resolved the issue.

**Comment by bkamapantula** [comment]
Thanks @markmacau! Your suggestion worked for me.

**Comment by marcjulianschwarz** [comment]
Using the `XDG_CACHE_HOME` variable works great but I was wondering whether there is a way to disable caching entirely? I have set caching to False in the OpenAI model, the guidance call and even the program call to be sure it's disabled everywhere. Still, guidance is trying to create a diskcache. Am I missing something?

**Comment by aniquetahir** [comment]
I'm facing the same issue where caching is happening even though it is set to disabled.
