### ISSUE TITLE
Support for Falcon models

### ISSUE THREAD

**Issue by mlmonk** [microsoft/guidance#165]
With the release of Falcon models and their permissive license, we can expect them to become extremely popular in the community. It would be great if the library supported the model out of the box. As of now, I get the following error while initializing Falcon-7B-Instruct in guidance as an llm.

```
model_id = "tiiuae/falcon-7b-instruct"
tokenizer = AutoTokenizer.from_pretrained(model_id)
guidance.llm = guidance.llms.Transformers(model=model_id, device_map="auto", trust_remote_code=True, tokenizer=tokenizer, torch_dtype=torch.bfloat16)`
```

The error is below:
```---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-33-f2a8438b16cb> in <module>
      1 # we use LLaMA here, but any GPT-style model will do
      2 import guidance
----> 3 guidance.llm = guidance.llms.Transformers(model="tiiuae/falcon-7b-instruct", device_map="auto", trust_remote_code=True, tokenizer=tokenizer, torch_dtype=torch.bfloat16,)

~/.local/lib/python3.8/site-packages/guidance/llms/_transformers.py in __init__(self, model, tokenizer, caching, token_healing, acceleration, temperature, device, **kwargs)
     44 
     45         self._prefix_ids = [self._tokenizer.bos_token_id, 100] # token ids that we use to decode tokens after a prefix
---> 46         self._prefix_str = self._tokenizer.decode(self._prefix_ids, fragment=False)
     47 
     48         self._token_prefix_map = self._build_token_prefix_map(model)

~/.local/lib/python3.8/site-packages/transformers/tokenization_utils_base.py in decode(self, token_ids, skip_special_tokens, clean_up_tokenization_spaces, **kwargs)
   3494         token_ids = to_py_obj(token_ids)
   3495 
-> 3496         return self._decode(
   3497             token_ids=token_ids,
   3498             skip_special_tokens=skip_special_tokens,

~/.local/lib/python3.8/site-packages/transformers/tokenization_utils_fast.py in _decode(self, token_ids, skip_special_tokens, clean_up_tokenization_spaces, **kwargs)
    547         if isinstance(token_ids, int):
    548             token_ids = [token_ids]
--> 549         text = self._tokenizer.decode(token_ids, skip_special_tokens=skip_special_tokens)
    550 
    551         clean_up_tokenization_spaces = (

TypeError: argument 'ids': 'NoneType' object cannot be interpreted as an integer

**Comment by synapsta** [comment]
I'd like to thank you folks for fixing the issue above so quickly! After pulling from master, I'm now able to load a Falcon model with guidance.llms.Transformers('tiiuae/falcon-7b-instruct', device='cuda', trust_remote_code=True), but when I try to use 'guided' generation, I get one correct output and then the following error message:

`Exception in thread Thread-13 (generate):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py", line 1515, in generate
    return self.greedy_search(
  File "/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py", line 2332, in greedy_search
    outputs = self(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/tiiuae/falcon-7b-instruct/22225c3ac76bdddc1c6c44ebea0e3109468de29f/modelling_RW.py", line 753, in forward
    transformer_outputs = self.transformer(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/tiiuae/falcon-7b-instruct/22225c3ac76bdddc1c6c44ebea0e3109468de29f/modelling_RW.py", line 614, in forward
    causal_mask = self._prepare_attn_mask(
  File "/root/.cache/huggingface/modules/transformers_modules/tiiuae/falcon-7b-instruct/22225c3ac76bdddc1c6c44ebea0e3109468de29f/modelling_RW.py", line 533, in _prepare_attn_mask
    expanded_attn_mask if combined_attention_mask is None else expanded_attn_mask | combined_attention_mask
RuntimeError: The size of tensor a (82) must match the size of tensor b (69) at non-singleton dimension 3`

I realize that is not much to go on and maybe I should open up a new and more complete ticket. I'm happy to do that. Just wanted to add this note to the existing issue in case the original poster was seeing the same thing.

If you want more info, just let me know. Thanks.
