### ISSUE TITLE
Select outputs duplicate strings for LLaMA-7B

### ISSUE THREAD

**Issue by lsc64** [microsoft/guidance#17]
My results with LLaMA-7B don't match the tutorial, please see some examples below.

```python
import guidance
guidance.llm = guidance.llms.Transformers('Neko-Institute-of-Science/LLaMA-7B-HF', device=0)
```

### 1. Character Creator
<details>
  <summary>Code (copied from readme)</summary>

  ```python
# we can pre-define valid option sets
valid_weapons = ["sword", "axe", "mace", "spear", "bow", "crossbow"]

# define the prompt
character_maker = guidance("""The following is a character profile for an RPG game in JSON format.
```json
{
    "id": "{{id}}",
    "description": "{{description}}",
    "name": "{{gen 'name'}}",
    "age": {{gen 'age' pattern='[0-9]+' stop=','}},
    "armor": "{{#select 'armor'}}leather{{or}}chainmail{{or}}plate{{/select}}",
    "weapon": "{{select 'weapon' options=valid_weapons}}",
    "class": "{{gen 'class'}}",
    "mantra": "{{gen 'mantra' temperature=0.7}}",
    "strength": {{gen 'strength' pattern='[0-9]+' stop=','}},
    "items": [{{#geneach 'items' num_iterations=5 join=', '}}"{{gen 'this' temperature=0.7}}"{{/geneach}}]
}```""")

# generate a character
character_maker(
    id="e1f491f7-7ab8-4dac-8c20-c92b5e7d883d",
    description="A quick and nimble fighter.",
    valid_weapons=valid_weapons
)
  ```
</details>

Result:

> The following is a character profile for an RPG game in JSON format.
> ```json
> {
>     "id": "e1f491f7-7ab8-4dac-8c20-c92b5e7d883d",
>     "description": "A quick and nimble fighter.",
>     "name": "Fighter",
>     "age": 18,
>     "armor": "plateplate",
>     "weapon": "swordsword",
>     "class": "fighter",
>     "mantra": "Weaponry is my strength.",
>     "strength": 10,
>     "items": ["sword", "armor", "helmet", "sword", "fishing pole"]
> }
> ```

`select` for the armor and weapon duplicates the output. 
### 2. Basic Templating
<details><summary>Code (copied from examples)</summary>
<p>
```python
prompt = guidance('''Is the following sentence offensive? Please answer with a single word, either "Yes", "No", or "Maybe".
Sentence: {{example}}
Answer:{{#select "answer" logprobs='logprobs'}} Yes{{or}} No{{or}} Maybe{{/select}}''')
prompt = prompt(example='I hate tacos')
prompt
```
</p>
</details> 
Result:

> Is the following sentence offensive? Please answer with a single word, either "Yes", "No", or "Maybe".
> Sentence: I hate tacos
> Answer: Yes Yes

<details><summary>Code (copied from examples)</summary>
<p>

```python
prompt = guidance('''Generate a response to the following email:
{{email}}.
Response:{{gen "response"}}

Is the response above offensive in any way? Please answer with a single word, either "Yes" or "No".
Answer:{{#select "answer" logprobs='logprobs'}} Yes{{or}} No{{/select}}''')
prompt = prompt(email='I hate tacos')
prompt
```
</p>
</details> 

> Generate a response to the following email:
> I hate tacos.
> Response: I hate tacos too.
> I hate tacos.
> Response: I hate tacos too. I hate tacos too.
> I hate tacos too.
> Response: I hate tacos too. I hate tacos too. I hate tacos too.
> I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate tacos too. I hate
> 
> Is the response above offensive in any way? Please answer with a single word, either "Yes" or "No".
> Answer: Yes Yes

`select` duplicates the Yes

**Comment by slundberg** [comment]
Thank you for bringing this up! That was an accidental side effect of fixing another bug yesterday. This is all fixed now with 0.0.46 (and the select statement runs faster now :) )
