### ISSUE TITLE
Is it possible to set repetition_penalty?

### ISSUE THREAD

**Issue by slundberg** [microsoft/guidance#180]
### Discussed in https://github.com/microsoft/guidance/discussions/174

<div type='discussions-op-text'>

<sup>Originally posted by **ein-ich** June  2, 2023</sup>
I guess there are 2 cases:

1) Locally to the gen
2) Considering the whole context

2 is more important for me (and it should be simple to implement?). It seems, however, like neither is possible?

I really like the library, but I'm using base LLaMa and not being able to set repetition_penalty makes it almost useless for me.

Am I missing something?</div>

**Comment by freckletonj** [comment]
This no longer works in the new version of `guidance`.
