### ISSUE TITLE
[Feature Request] Capture named blocks in variables

### ISSUE THREAD

**Issue by jonathanasdf** [microsoft/guidance#183]
It would be useful to be able to define a named block and get the underlying output that maps to the named block. For example in the JSON example in the main page currently to get just the JSON block out it would have to be reconstructed from the variables manually.

This should hopefully also automatically work for partials/includes as I believe those get interpreted as named blocks.

```
def test_guidance_block_output():
    program = guidance(
        "{{input}} {{#block 'joke'}}Why can't a pirate say the alphabet? {{gen max_tokens=30}}{{/block}}",
        llm=get_llm('transformers:gpt2')
    )
    output = program(
        input="Give me a joke.",
    )
    assert len(output["joke"]) > 0
```

**Comment by slundberg** [comment]
Thanks for noting this! That should actually have worked, but was clearly wasn't. I just pushed a fix!
