### ISSUE TITLE
Request for HuggingFace Text Generation Inference 

### ISSUE THREAD

**Issue by SupreethRao99** [microsoft/guidance#209]
It would be great if guidance supported LLM's deployed through HuggingFace text generation inference framework (https://github.com/huggingface/text-generation-inference). The library allows API calls to LLM in similar fashion to OpenAI. 
Adding this feature would make guidance more usable.

Thanks

**Comment by marioluan** [comment]
@SupreethRao99 Why did you close this? I believe this is still relevant and not yet supported.
