### ISSUE TITLE
Open AI: Add `frequency_penalty` and `presence_penalty` support

### ISSUE THREAD

**Issue by jelling** [microsoft/guidance#212]
**Is your feature request related to a problem? Please describe.**

It is not currently possible to pass  `frequency_penalty` and `presence_penalty`  to the `gen` tag.

However, the `library.gen()` function [appears to support this via `**llm_kwargs`](https://github.com/microsoft/guidance/blob/d6b855aa625677f806fc51ec7238d2a38df594ea/guidance/library/_gen.py#L58)

**Describe the solution you'd like**

Add support for passing these parameters to Open AI. And if possible, allow passing arbitrary params to the `gen()` via the `{{gen}}`

**Describe alternatives you've considered**

I thought of calling library.gen() directly but couldn't find any examples of how to do this.

**Comment by chrisfentiman** [comment]
@jelling - This is in the main branch now; see the thread here: https://github.com/microsoft/guidance/discussions/174#discussioncomment-6079036.
