### ISSUE TITLE
Placeholders in chat roles

### ISSUE THREAD

**Issue by MichaelOwenDyer** [microsoft/guidance#218]
**Is your feature request related to a problem? Please describe.**
I do not currently know of a way to use chat roles (such as `{{#assistant~}}`) where the concrete role used is determined by the function arguments.

**Describe the solution you'd like**
I would like to be able to have an input such as
`messages=[
                      {
                          "role": "user",
                          "content": "Hi"
                      },
                      {
                          "role": "assistant",
                          "content": "Hi there! How can I help you today?"
                      },
                      {
                          "role": "user",
                          "content": "I want to get the first element out of a set but I can't figure out how"
                      },
                  ]
`
and be able to use it in the template like so:
`
{{#each messages}}
{{#{{this.role}}~}}
{{this.content}}
{{~/{{this.role}}}}
{{~/each}}
`

**Describe alternatives you've considered**
Formatting the template string in advance before feeding it to guidance, or just labelling the messages with the role in plain text instead of using the role tags.

**Additional context**
I am currently using OpenAI for my testing

**Comment by boukeversteegh** [comment]
In one of the examples, this syntax is used. I haven't tried it but perhaps it works for you.

```handlebars
{{#each practice}}
{{#if (== this.role "user")}}
{{#user}}{{this.content}}{{/user}}
{{else}}
{{#assistant}}{{this.content}}{{/assistant}}
{{/if}}
{{/each}}
```

https://github.com/microsoft/guidance/blob/d6b855aa625677f806fc51ec7238d2a38df594ea/notebooks/tutorial.ipynb#L1203-L1209

**Comment by MichaelOwenDyer** [comment]
Thank you for the idea, it worked! I ended up using three if statements to support all three roles, like so:
```
{{#each messages}}
{{#if (== this.role "user")}}{{#user~}}{{this.content}}{{~/user}}{{/if}}
{{#if (== this.role "assistant")}}{{#assistant~}}{{this.content}}{{~/assistant}}{{/if}}
{{#if (== this.role "system")}}{{#system~}}{{this.content}}{{~/system}}{{/if}}
{{~/each}}
```
