### ISSUE TITLE
Full syntax of Guidance with examples

### ISSUE THREAD

**Issue by SergiyBarskyy** [microsoft/guidance#235]
Please can you tell me if I can see the full syntax of Microsoft Guidance with examples somewhere?

**Comment by slundberg** [comment]
We are still working on that :) ...it will live in https://guidance.readthedocs.io eventually. There is the language syntax, and also the command API, complete docs for both is a work in progress.

**Comment by SergiyBarskyy** [comment]
It is fantastic! Thanks a lot Scott.
