### ISSUE TITLE
Make inferences from each iteration in each blocks available as output

### ISSUE THREAD

**Issue by rveldhoven** [microsoft/guidance#24]
I'm not sure if this is already possible, if so maybe an example could be included in the README? I was not able to find functionality that enables this.

It would be nice if all inferences in {{each}} blocks are available as output variables. Currently only the last generation is available as a named variable.

For example say the following guidance program is executed:

```
choices = ['odd', 'correct']

program = guidance("""
You are a helpful and terse assistant.

You have to check each of the following sentences for odd grammar and give a judgement.

{{#each sentences}}
Sentence {{@index}}: ```{{this}}```: Judgement: (Respond with 'correct' or 'odd' only!) {{select 'judgement' options=choices}}
{{/each}}""")

outputs = program(
    sentences=a_list_of_sentences,
    choices=choices
)().variables

print(outputs)
```

Will only output the last generated 'judgement':

`{'llm': <guidance.llms._openai.OpenAI object at 0x0000025BA1A44B90>, 'sentences': ['sentence1', 'sentence2', 'sentence3'], 'choices': ['odd', 'correct'], 'judgement': 'odd'}`

A much better result would be:

`{'llm': <guidance.llms._openai.OpenAI object at 0x0000025BA1A44B90>, 'sentences': ['sentence1', 'sentence2', 'sentence3'], 'choices': ['odd', 'correct'], 'judgement': ['odd', 'correct', 'odd']}`

**Comment by slundberg** [comment]
Hey! Great point. We want to maintain a simple model of memory for guidance programs that matches how normal programs work, which means overwriting variables when you set them. However, we have option named `list_append=True` that you can add for the `gen` command that will make a list just like you want, I just pushed support for `list_append` in the `select` command as well. So if you pull master you can do this:

```python
import guidance

guidance.llm = guidance.llms.OpenAI("text-davinci-003")

choices = ['odd', 'correct']

a_list_of_sentences = [
    'I am a sentence.',
    'I am a sentence too.',
    'I am a sentence three.'
]

program = guidance("""
You are a helpful and terse assistant.

You have to check each of the following sentences for odd grammar and give a judgement.

{{#each sentences}}
Sentence {{@index}}: ```{{this}}```: Judgement: (Respond with 'correct' or 'odd' only!) {{select 'judgement' list_append=True options=choices}}
{{/each}}""")

outputs = program(
    sentences=a_list_of_sentences,
    choices=choices
)().variables()

print(outputs)
```

gives

```{'llm': <guidance.llms._openai.OpenAI object at 0x7f8424542d00>, 'sentences': ['I am a sentence.', 'I am a sentence too.', 'I am a sentence three.'], 'choices': ['odd', 'correct'], 'judgement': ['correct', 'correct', 'odd']}```
