### ISSUE TITLE
import guidance is not working

### ISSUE THREAD

**Issue by VarunGumma** [microsoft/guidance#266]
**The bug**
I am trying to use this library by importing guidance and I get the following error: ```pp.ParserElement.enable_packrat()
AttributeError: type object 'ParserElement' has no attribute 'enable_packrat'. Did you mean: 'enablePackrat'?```

If I try to go the source file and correct it, many other similar errors pop up.

**To Reproduce**
```python
import guidance
```

**System info (please complete the following information):**
 - System: ```WSL Ubuntu 22.04.2```
 - Guidance Version (`guidance.__version__`): ```NA``` (can't even import)

**Comment by slundberg** [comment]
Thanks! Just pushed a fix that adds pyparsing>=3.0.0 to setup.py (you need version 3 of pyparsing)
