### ISSUE TITLE
Generated text not respecting pattern

### ISSUE THREAD

**Issue by Ryul0rd** [microsoft/guidance#29]
I'm trying to generate some text using a modified version of the main example and am running into an issue where the model is picking a token containing a non-numerical character for the 'chapter' variable despite that not matching the pattern. Here's my code:
```
prompt = '''
Tweak this proverb to apply to machine learning model instructions instead.

{{proverb}}
- {{book}} {{chapter}}:{{verse}}

UPDATED
Where there is no guidance{{gen 'rewrite' stop='- '}}
- GPT {{gen 'chapter' pattern='[0-9]' max_tokens=1}}:{{gen 'verse' pattern='[0-9]+' stop='\\n'}}
'''[1:-1]

model = guidance.llms.Transformers('stabilityai/stablelm-base-alpha-3b', device=0)
program = guidance(prompt, llm = model)
executed_program = program(
    proverb="Where there is no guidance, a people falls,\nbut in an abundance of counselors there is safety.",
    book="Proverbs",
    chapter=11,
    verse=14,
)

print(executed_program)
print(executed_program["chapter"])
```
and the generated output:
```
Tweak this proverb to apply to machine learning model instructions instead.

Where there is no guidance, a people falls,
but in an abundance of counselors there is safety.
- Proverbs 11:14

UPDATED
Where there is no guidance, a people falls, but in an abundance of counselors there is safety.

- GPT 2::2
2:
```
I should also add that I saw a similar issue earlier today with pattern not working as intended so I made sure I was on the latest version just before running this just now.

**Comment by slundberg** [comment]
Thanks! This turned out to be a case where the max tokens stopping criteria fired before the ":" end criteria. Reversing this order proved to be a pain, but I think I have a patch now. Will push soon. Note also that `max_tokens=1` might look like it would prevent the ":" from firing, but the "2" is actually joined to the prior space into " 2" (because of token healing) and hence does not count towards the max_tokens limit.

**Comment by Ryul0rd** [comment]
@slundberg I grabbed the latest version just now and am still getting the same issue when I use "OpenAssistant/oasst-sft-4-pythia-12b-epoch-3.5" as my model instead. Interestingly, I can get the desired behavior by setting `max_tokens=2`, `max_tokens=0`, or omitting `max_tokens` entirely but it's still generating a ":" when `max_tokens=1`.
