### ISSUE TITLE
Select block returning options twice

### ISSUE THREAD

**Issue by lakshyaag** [microsoft/guidance#30]
When using `{{select}}`, the same response is returned twice. I have tested it with `text-davinci-003`, so not sure if it applies to other local models.

## Example 1:
![image](https://github.com/microsoft/guidance/assets/10924399/64248b77-c87d-4418-b490-d37efd433bd0)

Here,
Expected output: `Anachronism: Yes`
Actual output: `Anachronism: Yes Yes`

## Example 2:
![image](https://github.com/microsoft/guidance/assets/10924399/b1101b5b-8e67-497f-bf64-39da2cce30de)

Here,
1. Expected output: `armor: leather`
Actual output: `armor: leatherleather`

2. Expected output: `weapon: sword`
Actual output: `weapon: swordsword`

**Comment by gmonair** [comment]
Try upgrading to the latest version, according to #17 this was fixed.

**Comment by lakshyaag** [comment]
Oh, great, thank you for bringing this to my attention. I'll close the issue 😀
