### ISSUE TITLE
ValueError: No valid option generated in #select!

### ISSUE THREAD

**Issue by lukaemon** [microsoft/guidance#31]
Just walking through the tutorial. 

```python
guidance.llm = guidance.llms.OpenAI("text-curie-001")

p = guidance('''Is the following sentence offensive? Yes, no, or maybe.
Sentence: {{example}}
Answer: {{#select 'answer' logprobs='logprobs'}} Yes{{or}} No{{or}} Maybe{{/select}}''')

p = p(example='You are such an asshole!')
```

What did I miss? 

ps: `text-davinci-003` failed as well.

**Comment by slundberg** [comment]
Short answer is that you are asking for two spaces after `Answer:` and GPT does not want to do that. Long answer is I'll look into why we failed to force GPT to do that (probably we didn't add enough log-rob bias :) )

**Comment by lukaemon** [comment]
Oh my lol. Thanks for pointing that out.
