### ISSUE TITLE
role_simulator function and encountered a KeyError for the 'first_question' variable

### ISSUE THREAD

**Issue by iAsimov** [microsoft/guidance#34]
Hello,

I've been using your role_simulator function and encountered a KeyError for the 'first_question' variable. The error message suggests that 'first_question' should have been passed as an argument when calling the program, or it should have been set as a default value when creating the program.

Here's the code that's causing the error:

```
role_simulator = guidance('''
...
{{#if first_question}}You can also start the conversation.{{/if}}
...
{{#if first_question}}Let me start the conversation now:
{{role}}: {{first_question}}{{/if}}
...
''')

republican = role_simulator(role='Republican')
democrat = role_simulator(role='Democrat')

first_question = '''What do you think is the best way to stop inflation?'''
...
```

The error occurs because 'first_question' is not defined at the time when the role_simulator function is called.

**Comment by slundberg** [comment]
Thanks! That was a typo...just fixed it. It should say:
```
republican = role_simulator(role='Republican', await_missing=True)
democrat = role_simulator(role='Democrat', await_missing=True)
```

Right now we throw an error when a variable is missing, but in the future once we have some more obvious notation on the output we plan to allow all missing features to be automatically awaited (so you can more easily build partial templates like this). But for now we need to include `await_missing=True` to avoid throwing an error.
