### ISSUE TITLE
The OpenAI API does not currently support partial assistant prompting. tutorial.py section 21 Agents

### ISSUE THREAD

**Issue by dwcar49us** [microsoft/guidance#41]
installed on windows 10 with Anaconda Python 3.10.9  openai-0.27.6
ran pip install guidance
notebook tutorial.ipynb worked until section 21

Traceback

Traceback (most recent call last):
  File "C:\Users\David\AppData\Roaming\Python\Python310\site-packages\guidance\library\_geneach.py", line 143, in geneach
    gen_obj = await parser.llm_session(strip_markers(parser.prefix), stop=stop, max_tokens=len(stop_tokens)+2, temperature=0, cache_seed=0)
  File "C:\Users\David\AppData\Roaming\Python\Python310\site-packages\guidance\llms\_openai.py", line 310, in __call__
    out = self.llm.caller(**call_args)
  File "C:\Users\David\AppData\Roaming\Python\Python310\site-packages\guidance\llms\_openai.py", line 186, in _library_call
    kwargs['messages'] = prompt_to_messages(kwargs['prompt'])
  File "C:\Users\David\AppData\Roaming\Python\Python310\site-packages\guidance\llms\_openai.py", line 24, in prompt_to_messages
    assert prompt.endswith("<|im_start|>assistant\n"), "When calling OpenAI chat models you must generate only directly inside the assistant role! The OpenAI API does not currently support partial assistant prompting."
AssertionError: When calling OpenAI chat models you must generate only directly inside the assistant role! The OpenAI API does not currently support partial assistant prompting.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\David\AppData\Roaming\Python\Python310\site-packages\guidance\_program_executor.py", line 94, in run
    await self.visit(self.parse_tree)
  File "C:\Users\David\AppData\Roaming\Python\Python310\site-packages\guidance\_program_executor.py", line 423, in visit
    visited_children.append(await self.visit(child, inner_next_node, inner_next_next_node, inner_prev_node, node, parent_node))
  File "C:\Users\David\AppData\Roaming\Python\Python310\site-packages\guidance\_program_executor.py", line 423, in visit
    visited_children.append(await self.visit(child, inner_next_node, inner_next_next_node, inner_prev_node, node, parent_node))
  File "C:\Users\David\AppData\Roaming\Python\Python310\site-packages\guidance\_program_executor.py", line 390, in visit
    command_output = await command_function(*positional_args, **named_args)
  File "C:\Users\David\AppData\Roaming\Python\Python310\site-packages\guidance\library\_geneach.py", line 145, in geneach
    raise Exception(f"Error generating stop tokens for geneach loop. Perhaps you are outside of role tags (assistant/user/system)? If you don't want the loop to check for stop tokens, set stop=False or set num_iterations.")
Exception: Error generating stop tokens for geneach loop. Perhaps you are outside of role tags (assistant/user/system)? If you don't want the loop to check for stop tokens, set stop=False or set num_iterations.

Error in program:  Error generating stop tokens for geneach loop. Perhaps you are outside of role tags (assistant/user/system)? If you don't want the loop to check for stop tokens, set stop=False or set num_iterations.
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
File ~\AppData\Roaming\Python\Python310\site-packages\guidance\library\_geneach.py:143, in geneach(list_name, stop, max_iterations, min_iterations, num_iterations, hidden, join, single_call, single_call_temperature, single_call_max_tokens, single_call_top_p, _parser_context)
    142 try:
--> 143     gen_obj = await parser.llm_session(strip_markers(parser.prefix), stop=stop, max_tokens=len(stop_tokens)+2, temperature=0, cache_seed=0)
    144 except Exception:

File ~\AppData\Roaming\Python\Python310\site-packages\guidance\llms\_openai.py:310, in OpenAISession.__call__(self, prompt, stop, stop_regex, temperature, n, max_tokens, logprobs, top_p, echo, logit_bias, token_healing, pattern, stream, cache_seed, caching)
    309         call_args["logit_bias"] = {str(k): v for k,v in logit_bias.items()} # convert keys to strings since that's the open ai api's format
--> 310     out = self.llm.caller(**call_args)
    312 except openai.error.RateLimitError:

File ~\AppData\Roaming\Python\Python310\site-packages\guidance\llms\_openai.py:186, in OpenAI._library_call(self, **kwargs)
    185 if self.chat_mode:
--> 186     kwargs['messages'] = prompt_to_messages(kwargs['prompt'])
    187     del kwargs['prompt']

File ~\AppData\Roaming\Python\Python310\site-packages\guidance\llms\_openai.py:24, in prompt_to_messages(prompt)
     21 # if len(start_tags) != len(end_tags):
     22 #     raise MalformedPromptException("Malformed prompt: start and end tags are not properly paired")
---> 24 assert prompt.endswith("<|im_start|>assistant\n"), "When calling OpenAI chat models you must generate only directly inside the assistant role! The OpenAI API does not currently support partial assistant prompting."
     26 pattern = r'<\|im_start\|>(\w+)(.*?)(?=<\|im_end\|>|$)'

AssertionError: When calling OpenAI chat models you must generate only directly inside the assistant role! The OpenAI API does not currently support partial assistant prompting.

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
Cell In[21], line 13
      1 prompt = guidance(
      2 '''{{#system~}}
      3 You are a helpful assistant
   (...)
     11 {{~/assistant}}
     12 {{~/geneach}}''')
---> 13 prompt= prompt(user_text ='hi there')
     14 prompt

File ~\AppData\Roaming\Python\Python310\site-packages\guidance\_program.py:225, in Program.__call__(self, **kwargs)
    223     loop = asyncio.new_event_loop()
    224     loop.create_task(new_program.update_display.run()) # start the display updater
--> 225     loop.run_until_complete(new_program.execute())
    227 return new_program

File C:\anaconda3\lib\site-packages\nest_asyncio.py:90, in _patch_loop.<locals>.run_until_complete(self, future)
     87 if not f.done():
     88     raise RuntimeError(
     89         'Event loop stopped before Future completed.')
---> 90 return f.result()

File C:\anaconda3\lib\asyncio\futures.py:201, in Future.result(self)
    199 self.__log_traceback = False
    200 if self._exception is not None:
--> 201     raise self._exception.with_traceback(self._exception_tb)
    202 return self._result

File C:\anaconda3\lib\asyncio\tasks.py:232, in Task.__step(***failed resolving arguments***)
    228 try:
    229     if exc is None:
    230         # We use the `send` method directly, because coroutines
    231         # don't have `__iter__` and `__next__` methods.
--> 232         result = coro.send(None)
    233     else:
    234         result = coro.throw(exc)

File ~\AppData\Roaming\Python\Python310\site-packages\guidance\_program.py:311, in Program.execute(self)
    309 else:
    310     with self.llm.session(asynchronous=True) as llm_session:
--> 311         await self._executor.run(llm_session)
    312 self._text = self._executor.prefix
    314 # delete the executor and so mark the program as not executing

File ~\AppData\Roaming\Python\Python310\site-packages\guidance\_program_executor.py:98, in ProgramExecutor.run(self, llm_session)
     96 print(traceback.format_exc())
     97 print("Error in program: ", e)
---> 98 raise e

File ~\AppData\Roaming\Python\Python310\site-packages\guidance\_program_executor.py:94, in ProgramExecutor.run(self, llm_session)
     88 self.llm_session = llm_session
     89 try:
     90     # first parse all the whitespace control
     91     # self.whitespace_control_visit(self.parse_tree)
     92 
     93     # now execute the program
---> 94     await self.visit(self.parse_tree)
     95 except Exception as e:
     96     print(traceback.format_exc())

File ~\AppData\Roaming\Python\Python310\site-packages\guidance\_program_executor.py:423, in ProgramExecutor.visit(self, node, next_node, next_next_node, prev_node, parent_node, grandparent_node)
    421     else:
    422         inner_prev_node = prev_node
--> 423     visited_children.append(await self.visit(child, inner_next_node, inner_next_next_node, inner_prev_node, node, parent_node))
    424 # visited_children = [self.visit(child) for child in node.children]
    426 if len(visited_children) == 1:

File ~\AppData\Roaming\Python\Python310\site-packages\guidance\_program_executor.py:423, in ProgramExecutor.visit(self, node, next_node, next_next_node, prev_node, parent_node, grandparent_node)
    421     else:
    422         inner_prev_node = prev_node
--> 423     visited_children.append(await self.visit(child, inner_next_node, inner_next_next_node, inner_prev_node, node, parent_node))
    424 # visited_children = [self.visit(child) for child in node.children]
    426 if len(visited_children) == 1:

File ~\AppData\Roaming\Python\Python310\site-packages\guidance\_program_executor.py:390, in ProgramExecutor.visit(self, node, next_node, next_next_node, prev_node, parent_node, grandparent_node)
    388 # call the optionally asyncronous command
    389 if inspect.iscoroutinefunction(command_function):
--> 390     command_output = await command_function(*positional_args, **named_args)
    391 else:
    392     command_output = command_function(*positional_args, **named_args)

File ~\AppData\Roaming\Python\Python310\site-packages\guidance\library\_geneach.py:145, in geneach(list_name, stop, max_iterations, min_iterations, num_iterations, hidden, join, single_call, single_call_temperature, single_call_max_tokens, single_call_top_p, _parser_context)
    143     gen_obj = await parser.llm_session(strip_markers(parser.prefix), stop=stop, max_tokens=len(stop_tokens)+2, temperature=0, cache_seed=0)
    144 except Exception:
--> 145     raise Exception(f"Error generating stop tokens for geneach loop. Perhaps you are outside of role tags (assistant/user/system)? If you don't want the loop to check for stop tokens, set stop=False or set num_iterations.")
    146 if gen_obj["choices"][0]["finish_reason"] == "stop":
    147     break

Exception: Error generating stop tokens for geneach loop. Perhaps you are outside of role tags (assistant/user/system)? If you don't want the loop to check for stop tokens, set stop=False or set num_iterations.

**Comment by slundberg** [comment]
Thanks! I didn't realize that tutorial needs so much clean up :) That is fixed now, and lots more comments and cleaner use of role tags is in there.
