### ISSUE TITLE
tutorial.ipynb "Using Tools" IncompleteParseError

### ISSUE THREAD

**Issue by dwcar49us** [microsoft/guidance#45]
installed on windows 10 with Anaconda Python 3.10.9 openai-0.27.6
ran pip install guidance
notebook tutorial.ipynb worked until "Using Tools" section

IncompleteParseError                      Traceback (most recent call last)
Cell In[8], line 87
     35 program = guidance('''
     36 {{#system~}}
     37 You are a helpful assistant.
   (...)
     82 {{~/assistant}}
     83 ''')
     85 query = "What is Facebook's stock price right now?"
---> 87 program = program(
     88     user_query=query,
     89     search=search,
     90     is_search=is_search,
     91     practice=practice_round
     92 )

File ~\AppData\Roaming\Python\Python310\site-packages\guidance\_program.py:204, in Program.__call__(self, **kwargs)
    195 new_program = Program(
    196     text=self.marked_text,
    197 
   (...)
    200     **{**{k: v if callable(v) else copy.deepcopy(v) for k,v in self._variables.items()}, **kwargs}
    201 )
    203 # create an executor for the new program (this also marks the program as executing)
--> 204 new_program._executor = ProgramExecutor(new_program)
    206 # if we are in async mode schedule the program in the current event loop
    207 if new_program.async_mode:

File ~\AppData\Roaming\Python\Python310\site-packages\guidance\_program_executor.py:50, in ProgramExecutor.__init__(self, program)
     48 except parsimonious.exceptions.ParseError as e:
     49     self._check_for_simple_error(text)
---> 50     raise e

File ~\AppData\Roaming\Python\Python310\site-packages\guidance\_program_executor.py:47, in ProgramExecutor.__init__(self, program)
     45 # parse the program text
     46 try:
---> 47     self.parse_tree = grammar.parse(text)
     48 except parsimonious.exceptions.ParseError as e:
     49     self._check_for_simple_error(text)

File ~\AppData\Roaming\Python\Python310\site-packages\parsimonious\grammar.py:112, in Grammar.parse(self, text, pos)
    106 """Parse some text with the :term:`default rule`.
    107 
    108 :arg pos: The index at which to start parsing
    109 
    110 """
    111 self._check_default_rule()
--> 112 return self.default_rule.parse(text, pos=pos)

File ~\AppData\Roaming\Python\Python310\site-packages\parsimonious\expressions.py:143, in Expression.parse(self, text, pos)
    141 node = self.match(text, pos=pos)
    142 if node.end < len(text):
--> 143     raise IncompleteParseError(text, node.end, self)
    144 return node

IncompleteParseError: Rule 'template' matched in its entirety, but it didn't consume all the text. The non-matching portion of the text begins with '{{#each practice}}
{' (line 14, column 1).

**Comment by jsl9208** [comment]
same problem. resolved by upgrading to version 0.0.48

**Comment by dwcar49us** [comment]
version 0.0.48 of what?

**Comment by slundberg** [comment]
Thanks for reporting this! I updated the tutorial.ipynb to fix a typo (and add lots more comments, cleaning etc.) and this should be fixed now.
