### ISSUE TITLE
error while using guidance with azure openai

### ISSUE THREAD

**Issue by jhkim-tf** [microsoft/guidance#54]
**The bug**

ValueError: Fail to create device flow. Err: {
    "error": "invalid_request",
    "error_codes": [
        900144
    ],
....
}

**To Reproduce**
Give a full working code snippet that can be pasted into a notebook cell or python file. Make sure to include the LLM load step so we know which model you are using.
```python
# put your code snippet here
```

**System info (please complete the following information):**
 - OS (e.g. Ubuntu, Windows 11, Mac OS, etc.):
 - Guidance Version (`guidance.__version__`):

**Comment by somisawa** [comment]
This causes because `AzureOpenAI` uses `msal`. If you are unfamiliar with Azure and simplily wanna use Azure OpenAI Servise, try [my temporary solution](https://github.com/microsoft/guidance/issues/87#issuecomment-1556763491) #87

**Comment by somisawa** [comment]
@jhkim-tf

**Comment by marcotcr** [comment]
I think this is fixed now. If not, please reopen and give us a snippet to reproduce.
