### ISSUE TITLE
AuthenticationError: <empty message>

### ISSUE THREAD

**Issue by thistleknot** [microsoft/guidance#69]
**The bug**

**To Reproduce**
Give a full working code snippet that can be pasted into a notebook cell or python file. Make sure to include the LLM load step so we know which model you are using.
```python
import guidance

# set the default language model used to execute guidance programs
guidance.llm = guidance.llms.OpenAI("text-davinci-003")

# define a guidance program that adapts a proverb
program = guidance("""Tweak this proverb to apply to model instructions instead.

{{proverb}}
- {{book}} {{chapter}}:{{verse}}

UPDATED
Where there is no guidance{{gen 'rewrite' stop="\\n-"}}
- GPT {{gen 'chapter'}}:{{gen 'verse'}}""")

# execute the program on a specific proverb
executed_program = program(
    proverb="Where there is no guidance, a people falls,\nbut in an abundance of counselors there is safety.",
    book="Proverbs",
    chapter=11,
    verse=14
)
```

How do I authenticate with openai using this library.  The readme lacks it, I looked for "authe" in some of the api documents.

**System info (please complete the following information):**
 - OS (e.g. Ubuntu, Windows 11, Mac OS, etc.):
 - Windows 10, python 3.9
 - Guidance Version (`guidance.__version__`):

**Comment by marcotcr** [comment]
Either set the environment variable `OPENAI_API_KEY`, or have your token in a file under `~/.openai_api_key`.
We'll improve the documentation, thanks :)

**Comment by thistleknot** [comment]
I should add that I did try the obvious

import os
import openai
openai.organization = "org-LlcENoSg8JwddvvJKEzo7k0u"
openai.api_key = os.getenv("OPENAI_API_KEY")
openai.Model.list()

**Comment by thistleknot** [comment]
![image](https://github.com/microsoft/guidance/assets/5154106/247fc119-d67b-4671-8cb1-44bde17fe2d3)

**Comment by thistleknot** [comment]
ah

os.environ['OPENAI_API_KEY'] = 'mykey'
