### ISSUE TITLE
Import fails on Windows 10

### ISSUE THREAD

**Issue by 10c8** [microsoft/guidance#7]
**Issue:** Library fails to import on Windows 10 because `termios` has no Windows package.
**Possible Solutions:** Instead of `termios`, we must import `msvcrt`. For the pseudoterminals (`pty`), one could perhaps look at using [andfoy/pywinpty](https://github.com/andfoy/pywinpty).
**Stacktrace:**

```
File [{...}\lib\site-packages\guidance\library\__init__.py:1]({...}/lib/site-packages/guidance/library/__init__.py:1)
----> 1 from ._shell import shell
      2 from ._gen import gen
      3 from ._await import await_

File [{...}\lib\site-packages\guidance\library\_shell.py:7]({...}/lib/site-packages/guidance/library/_shell.py:7)
      5 import os
      6 import subprocess
----> 7 import pty
      8 import asyncio
     11 def shell(command, partial_output, safe=True):

File [{...}\lib\pty.py:12]({...}/lib/pty.py:12)
     10 import os
     11 import sys
---> 12 import tty
     14 __all__ = ["openpty","fork","spawn"]
     16 STDIN_FILENO = 0

File [{...}\lib\tty.py:5]({...}/lib/tty.py:5)
      1 """Terminal utilities."""
      3 # Author: Steen Lumholt.
----> 5 from termios import *
      7 __all__ = ["setraw", "setcbreak"]
      9 # Indexes for termios list.

ModuleNotFoundError: No module named 'termios'
```

**Code reference:** https://github.com/microsoft/guidance/blob/ff31b31177ee9ad036ef5130daada5008444c734/guidance/library/_shell.py#LL7C11-L7C11

**Comment by slundberg** [comment]
Thanks! Just pushed a fix that makes `pty` optional. (It is only used right now for shell command calls with terminal history...an infrequent use case I think)
