### ISSUE TITLE
Missing model gpt-4-32k in list of `chat_models`.

### ISSUE THREAD

**Issue by prescod** [microsoft/guidance#77]
https://github.com/microsoft/guidance/blob/aefb45f29090997258bb9760721109931408c926/guidance/llms/_openai.py#L64

**Comment by slundberg** [comment]
Good catch! Want to send a PR to add it?

**Comment by flavius-popan** [comment]
Had a few spare minutes during lunch, hope you don't mind that I took care of this @prescod!
