### ISSUE TITLE
No valid option generated in #select when options don't start with spaces

### ISSUE THREAD

**Issue by Ryul0rd** [microsoft/guidance#79]
**The bug**
When I run the code below, I get the following error:
`ValueError: No valid option generated in #select! Please post a GitHub issue since this should not happen :)`

**To Reproduce**
```python
# doesn't work
guidance(
    "Hello, {{#select 'name'}}Alice{{or}}Bob{{/select}}",
    llm=guidance.llms.Transformers("gpt2"),
)()

# works
guidance(
    "Hello,{{#select 'name'}} Alice{{or}} Bob{{/select}}",
    llm=guidance.llms.Transformers("gpt2"),
)()
```

**System info (please complete the following information):**
 - OS: PopOS 22.04
 - Guidance Version (`guidance.__version__`): 0.0.49

**Comment by Mihaiii** [comment]
Should be clone of #67 for which I opened #78 .
