### ISSUE TITLE
Select syntax consistently picks arbitrary answer

### ISSUE THREAD

**Issue by Ryul0rd** [microsoft/guidance#80]
**The bug**
Select syntax, both the kind where you pass a list and the kind where you specify options in prompt, will not select the answer the model actually considers to be most likely. It will instead pick a random but consistent output. In this example, it reliably predicts 'red' regardless of the true label. If we omit 'red' as an option, it reliably predicts 'yellow' instead. 

**To Reproduce**
There are 3 lines in the prompt that are commented out and you must uncomment one to get it to run. The first line lets the model do freeform generation, showing that it knows the correct answer here when we don't use select syntax. The second and third lines are different versions of the select syntax and they both will consistently output the same random choice.
```python
model = guidance.llms.Transformers(
    model = GPTNeoXForCausalLM.from_pretrained('OpenAssistant/oasst-sft-4-pythia-12b-epoch-3.5', device_map='auto', load_in_8bit=True),
    tokenizer = GPTNeoXTokenizerFast.from_pretrained('OpenAssistant/oasst-sft-4-pythia-12b-epoch-3.5'),
)

options = ['red', 'green', 'blue', 'purple', 'yellow', 'orange', 'black', 'white']
options_with_spaces = [' ' + option for option in options]

prompt = guidance(
    (
        '<|prompter|>'
        'I own a {{color_label}} car. What color is the car?\n'
        '<|endoftext|><|assistant|>'
        # uncomment one of the following 3 lines
        #"The car is {{gen 'color_pred' max_tokens=3 stop=' ' temperature=0.0}}" # works
        #"The car is{{#select 'color_pred'}} red{{or}} green{{or}} blue{{or}} purple{{or}} yellow{{or}} orange{{or}} black{{/select}}." # doesn't work
        #"The car is{{select 'color_pred' options=options}}." # doesn't work
    ),
    llm=model,
)

total = 25
correct = 0
for _ in range(total):
    label = random.choice(options)
    pred = prompt(color_label=label, options=options_with_spaces)['color_pred'].strip().strip('.')
    print(label)
    print(pred)
    if pred == label:
        print('correct')
        correct += 1
    else:
        print('incorrect')
    print()
print(f'Accuracy: {correct / total * 100}%')
print(f'Chance Accuracy: {1 / len(options) * 100}%')
```

**System info (please complete the following information):**
 - OS (e.g. Ubuntu, Windows 11, Mac OS, etc.): PopOS 22.04
 - Guidance Version (`guidance.__version__`): 0.0.49

**Comment by slundberg** [comment]
Thank you so much for pointing this out. It was due to an "optimization" that was designed in the new select version pushed this to save on tokenization but ended up cutting off the all but the last 50 characters of the prefix. Now this should work with 0.0.51.

Thanks again!
