### ISSUE TITLE
Incorrect logprob values

### ISSUE THREAD

**Issue by Ryul0rd** [microsoft/guidance#82]
**The bug**
Extracting logprobs as described in the docs gives large positive values, but logprobs should always be negative or 0.

**To Reproduce**
```python
model = guidance.llms.Transformers(
    model = GPTNeoXForCausalLM.from_pretrained('OpenAssistant/oasst-sft-4-pythia-12b-epoch-3.5', device_map='auto', load_in_8bit=True),
    tokenizer = GPTNeoXTokenizerFast.from_pretrained('OpenAssistant/oasst-sft-4-pythia-12b-epoch-3.5'),
)

options = [' red', ' green', ' blue', ' purple', ' yellow', ' orange', ' black', ' white']
logprobs = guidance(
    (
        '<|prompter|>'
        'I own a {{color_label}} car. What color is the car?\n'
        '<|endoftext|><|assistant|>'
        "The car is{{select 'color_pred' options=options logprobs='logprobs'}}."
    ),
    llm=model,
)(color_label='red', options=options)['logprobs']

print(logprobs)
```
print results:
`{' red': tensor(120.9375), ' green': tensor(109.0781), ' blue': tensor(111.7734), ' black': tensor(109.9141), ' purple': tensor(109.5078), ' yellow': tensor(110.6016), ' orange': tensor(111.0547), ' white': tensor(108.6016)}`

**System info (please complete the following information):**
 - OS (e.g. Ubuntu, Windows 11, Mac OS, etc.): PopOS 22.04
 - Guidance Version (`guidance.__version__`): 0.0.51

**Comment by slundberg** [comment]
Sorry about all the select issues! Just fixed this on master

**Comment by Ryul0rd** [comment]
@slundberg No worries. Thanks for being so quick to respond. I'm still having some issues with logprobs on 0.0.52 though. The original example I posted here now gives me `ValueError: No valid option generated in #select! Please post a GitHub issue since this should not happen :)`

Additionally making some minor changes to this:
```python
model = guidance.llms.Transformers(
    model = GPTNeoXForCausalLM.from_pretrained('OpenAssistant/oasst-sft-4-pythia-12b-epoch-3.5', device_map='auto', load_in_8bit=True),
    tokenizer = GPTNeoXTokenizerFast.from_pretrained('OpenAssistant/oasst-sft-4-pythia-12b-epoch-3.5'),
)

options = ['red', 'green', 'blue', 'purple', 'yellow', 'orange', 'black', 'white'] # no more spaces
logprobs = guidance(
    (
        '<|prompter|>'
        'I own a {{color_label}} car. What color is the car?\n'
        '<|endoftext|><|assistant|>'
        "The car is {{select 'color_pred' options=options logprobs='logprobs'}}." # new space after 'is'
    ),
    llm=model,
)(color_label='red', options=options)['logprobs']

print(logprobs)
```
gives me nans for all my logprobs.

**Comment by slundberg** [comment]
I just pushed another set of `select` fixes to master. It works on all the tests I have right now, so let me know if it fails for you.

**Comment by Ryul0rd** [comment]
I did notice that the probabilities don't sum to 1. Is this intended? If so, everything looks good to me. Though I can see how that might be confusing to some people.
