### ISSUE TITLE
Error in program:  Error generating stop tokens for geneach loop.

### ISSUE THREAD

**Issue by Sam1320** [microsoft/guidance#84]
**The bug**
I am trying to set a stop token for the `geneach` command but I don't find a way to make it work.

**To Reproduce**
```python
import guidance
guidance.llm = guidance.llms.OpenAI('gpt-3.5-turbo')
guidance.llm.cache.clear()

prompt = guidance(
'''{{#system~}}
You are a helpful assistant
{{~/system}}
{{~#geneach 'conversation' stop='Final Answer:'~}}
{{#user~}}
{{set 'this.user_text' (await 'user_text')}}
{{~/user}}
{{#assistant~}}
{{gen 'this.ai_text' temperature=0 max_tokens=300}}
{{~/assistant}}
{{~/geneach}}''', stream=False, silent=True)

prompt = prompt(user_text ='Hello there :)')
prompt
```

In this specific example I am using `stop='Final Answer:` but it does not work with any string. 

I get the following error:
```
assert prompt.endswith("<|im_start|>assistant\n"), "When calling OpenAI chat models you must generate only directly inside the assistant role! The OpenAI API does not currently support partial assistant prompting."
...
File "[<local venv path>/lib/python3.9/site-packages/guidance/library/_geneach.py](https://file+.vscode-resource.vscode-cdn.net/home/sam/.venvs/offering/lib/python3.9/site-packages/guidance/library/_geneach.py)", line 145, in geneach
    raise Exception(f"Error generating stop tokens for geneach loop. Perhaps you are outside of role tags (assistant[/user/system](https://file+.vscode-resource.vscode-cdn.net/user/system))? If you don't want the loop to check for stop tokens, set stop=False or set num_iterations.")
Exception: Error generating stop tokens for geneach loop. Perhaps you are outside of role tags (assistant[/user/system](https://file+.vscode-resource.vscode-cdn.net/user/system))? If you don't want the loop to check for stop tokens, set stop=False or set num_iterations.
```

**System info (please complete the following information):**
 - OS: Ubuntu
 - Guidance Version (`guidance.__version__`): 0.0.51

**Comment by AI-Ahmed** [comment]
maybe there is a missing `{{#user~}}` in your prompt?

**Comment by samyrodriguez** [comment]
> maybe there is a missing `{{#user~}}` in your prompt?

Oh nice catch @AI-Ahmed but that was actually a copy-paste error. I updated the snipped above and double checked running again locally. Still get the same error.

**Comment by AI-Ahmed** [comment]
Another thing which is interesting... Why are you set user input as await function while it is just `str` input? 


Maybe you can just set this as 

```python 
'''
{{#user~}}
{{user_input}}
{{~/user}}
'''
```

**Comment by slundberg** [comment]
the `stop` parameter of geneach is what the LLM would generate instead of starting the next iteration of the loop. You can't control OpenAI chat models outside of the role tags right now (nor would they likely generate that stop sequence outside their role tags...

I suggest you do something like:
```{{#if (my_custom_end_check_function this.ai_text)}}{{break}}{{/if}}```

or you could just raise a StopIteration exception directly from your stop condition function and call it like this form inside the loop :
```{{my_custom_end_check_function ai.text}}```

**Comment by Sam1320** [comment]
@slundberg great, thanks for the tip!.
