### ISSUE TITLE
How can I train a model using documents

### ISSUE THREAD

**Issue by YoungGoofy** [microsoft/guidance#92]
Hi all! Started to study the tutorial of guidance, but nowhere did I see any examples of how can i train a language model using pdf or csv files. Could you point me in which direction to think and what to figure out?

**Comment by marcotcr** [comment]
Sorry, I do not see how your question is related to this repo. `guidance` has nothing to do with training language models at this point. Do we have something about pdf or csv files in any of our documentation?
